[package]
name = "loafjective-c"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
cstr_core = { version = "0.2.5", default-features = false }
libc = { version = "0.2.126", default-features = false }

[build-dependencies]
cc = "1.0.73"

[features]
default = ["std"]
std = []